In [2]:
import torch




In [20]:
loss = torch.zeros([1,1])
print(loss)

tensor([[0.]])


In [21]:
y = torch.tensor([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
pred = torch.tensor([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
y = y.reshape(-1,2)
pred = pred.reshape(-1,2)
print(y)
print(pred)

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
        [17, 18]])
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
        [17, 18]])


In [23]:
for i in range(9):
                    loss  += ((pred[i][0]- y[i][0])**2 +(pred[i][1]- y[i][1])**2)
print(loss)


tensor([[0.]])
